name: VMQZanZhu
version: '1.0-SNAPSHOT'
main: xyz.lzgzxs.vmqZanZhu.VMQZanZhu
api-version: '1.21'
folia-supported: true
commands:
  openvmq:
    description: 打开赞助订单
    usage: /<command> <赞助项目>
  vmqreload:
    description: 重载插件配置
    usage: /<command>
    permission: vmqzanzhu.admin
