name: MTZanZhu
version: '1.0-SNAPSHOT'
main: xyz.lzgzxs.mtZanZhu.MTZanZhu
api-version: '1.21'
folia-supported: true
commands:
  openvmq:
    description: 打开赞助订单
    usage: /<command> <赞助项目>
  vmqreload:
    description: 重载插件配置
    usage: /<command>
    permission: mtzanzhu.admin
  vmqprice:
    description: 创建自定义金额的赞助订单
    usage: /<command> <金额> [支付方式]